### ISSUE TITLE
Mongo db configuration section is mandatory but empty in the examples

### ISSUE THREAD

**Issue by zioproto** [icclab/hurtle_sm#2]
In the reference configuration files there is no mongo db configuration, everything is commented out. 

https://github.com/icclab/hurtle_sm/blob/master/etc/sm_ops2.cfg

However if there is no mongo section you get this error:

```
ubuntu@wp3-service-manager:~$ service_manager -c /home/ubuntu/disco/etc/sm.cfg
/usr/lib/python2.7/dist-packages/pkg_resources.py:1031: UserWarning: /home/ubuntu/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
  warnings.warn(msg, UserWarning)
Using CONFIG_PATH /home/ubuntu/disco/etc/sm.cfg
Traceback (most recent call last):
  File "/usr/local/bin/service_manager", line 5, in <module>
    pkg_resources.run_script('sm==0.4', 'service_manager')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1394, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/sm-0.4-py2.7.egg/EGG-INFO/scripts/service_manager", line 22, in <module>
    from sm import admin
  File "/usr/local/lib/python2.7/dist-packages/sm-0.4-py2.7.egg/sm/admin.py", line 30, in <module>
    db_host = CONFIG.get('mongo', 'host', False)
  File "/usr/local/lib/python2.7/dist-packages/sm-0.4-py2.7.egg/sm/config.py", line 28, in get
    value = ConfigParser.ConfigParser.get(self, section, option, raw, vars)
  File "/usr/lib/python2.7/ConfigParser.py", line 607, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'mongo'
```

If you just add the `[mongo]` section to the config file you get this

```
ubuntu@wp3-service-manager:~$ service_manager -c /home/ubuntu/disco/etc/sm.cfg
/usr/lib/python2.7/dist-packages/pkg_resources.py:1031: UserWarning: /home/ubuntu/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
  warnings.warn(msg, UserWarning)
Using CONFIG_PATH /home/ubuntu/disco/etc/sm.cfg
Traceback (most recent call last):
  File "/usr/local/bin/service_manager", line 5, in <module>
    pkg_resources.run_script('sm==0.4', 'service_manager')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1394, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/sm-0.4-py2.7.egg/EGG-INFO/scripts/service_manager", line 22, in <module>
    from sm import admin
  File "/usr/local/lib/python2.7/dist-packages/sm-0.4-py2.7.egg/sm/admin.py", line 32, in <module>
    raise RuntimeError('No MongoDB host specified in the configuration file.')
RuntimeError: No MongoDB host specified in the configuration file.
ubuntu@wp3-service-manager:~$
```

**Comment by michaelerne** [comment]
while the use of a mongodb is highly recommended, this needs to be fixed. I'll tackle this tomorrow
